### ISSUE TITLE
Regression in 0.11.2dev0 related to l2 norm workload

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/dpnp#1374] opened 2023-04-06 20:34 UTC
[L2 norm](https://github.com/adarshyoga/dpbench/blob/main/dpbench/benchmarks/l2_norm/l2_norm_dpnp.py) workload in dpbench fails with an execution timeout error when run with dpnp 0.11.2dev0. The dpbench infrastructure triggers an execution timeout when a workload is executing for more than a preset threshold (currently 240 secs).
 With 0.11.1 release, l2 norm executes successfully. So there has been a regression in 0.11.2dev0 that is causing l2 norm to hang or execute slower than before.
 
 **DPbench log with 0.11.2dev0:**
---------------------------------
================ implementation dpnp ========================
implementation: dpnp
error states: ErrorCodes.EXECUTION_TIMEOUT
error msg: Execution timed out

 **DPbench log with 0.11.1:**
---------------------------------
================ implementation dpnp ========================
implementation: dpnp
framework: dpnp
framework version: 0.11.1
setup time: 169901292
warmup time: 4000964311
teardown time: 300084
max execution times: 4761952821
min execution times: 4110616548
median execution times: 4695358688.5
repeats: 10
preset: S
validated: SUCCESS

**Comment by antonwolfy** [comment] 2023-06-19 11:44
The issue is fixed with _dpnp=0.12.0_, so closing the case.

**Closed by antonwolfy** 2023-06-19 11:44 UTC
