### ISSUE TITLE
meshgrid function examples with unsupported parameter

### ISSUE THREAD

**Issue by npolina4** [IntelPython/dpnp#1299] opened 2023-02-16 10:17 UTC
Function limitation:
Parameter ``sparse`` is supported only with default value ``False``.

Function examples (_sparse=True_):
```python
import matplotlib.pyplot as plt
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)
xx, yy = np.meshgrid(x, y, sparse=True)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
h = plt.contourf(x,y,z)
plt.show()
```

**Comment by antonwolfy** [comment] 2024-02-21 11:51
@npolina4, the issue is resolved with dpnp=0.14.0:
```python
>>> import dpnp as np
>>> x = np.arange(-5, 5, 0.1)
>>> y = np.arange(-5, 5, 0.1)
>>> xx, yy = np.meshgrid(x, y, sparse=True)
>>> np.__version__
'0.14.0+189.gfcddad2474'
```

**Closed by antonwolfy** 2024-02-21 11:51 UTC
